author: "Stefan Kofler & Paul Kraft"
author_url: https://quickbirdstudios.com
podspec: XCoordinator.podspec
docset_icon: Images/logo-single.png
github_url: https://github.com/quickbirdstudios/XCoordinator
hide_documentation_coverage: true
theme: fullwidth
clean: true
